title = "Bo Motlagh"
baseURL = "https://theboeffect.com/"
languageCode = "en-us"
theme = "airspace-hugo"
publishDir = "docs"

[menu]

  [[menu.header]]
    weight = 2
    name = "About Me"
    url = "/#intro"
  [[menu.header]]
    weight = 4
    name = "Contact Me"
    url = "/contact"


  [[menu.footer]]
    weight = 1
    name = "Blog"
    url = "https://bomotlagh.unitedeffects.com"
  [[menu.footer]]
    weight = 3
    name = "Contact"
    url = "/contact"
  [[menu.footer]]
    weight = 5
    name = "Twitter"
    url = "https://twitter.com/theboeffect"
  [[menu.footer]]
    weight = 6
    name = "United Effects"
    url = "https://unitedeffects.com"

# The site's parameters
[params]

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Personal Site of Bo Motlagh"
    subtitle = "I like to build tech..."

  [params.wrapper]
    enable = true
    title = "About Me"
    italic = "Currently Founder and CEO of United Effects LLC"
    paragraph = "I design, build and lead enterprise platforms, emerging technologies, and engineering organizations. I am passionate about building people centric products and culture. I've been called ambitious..."

  #[params.blog]
  #  enable = false
  #  title = "Get The Latest On What I'm doing"
  #  subtitle = "Catch up with me, anytime and anywhere"

  #[params.feature]
  #  enable = true
  #  title = "A Few Projects I Enjoyed"
  #  content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
  #  [params.feature.button]
  #    caption = "View Works"
  #    url = "#"

  [params.call]
    enable = true
    title = "Have you seen United Effects Core EOS?"
    paragraph = "Disconnected SaaS products create a drag on sales, engineering, and solution ROI. Core EOS provides a foundation to connect and organize users, customers, and data across your products with a single-pane view."
    [params.call.button]
      url = "https://unitedeffects.com"

  [params.contact]
    enable = true
    title = "Contact Me"
    email = "borzou@theboeffect.com"
    subtitle = "Happy to network!"
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "What can I help you with?"
      address = "Fort Washington, PA, USA"
      email = "Email: borzou@theboeffect.com"
      twitter = "Twitter: @theBoEffect"
    [params.contact.gmaps]
      title = "If you're local, lets grab a coffee!"