title = "Bo Motlagh"
baseURL = "https://bomotlagh.com/"
languageCode = "en-us"
theme = "airspace-hugo"
publishDir = "docs"

[menu]

  [[menu.header]]
    weight = 2
    name = "About Me"
    url = "/#intro"
#  [[menu.header]]
#    weight = 4
#    name = "Contact Me"
#    url = "https://calendly.com/ue-bo/hello"


#  [[menu.footer]]
#    weight = 1
#    name = "Blog"
#    url = "https://bomotlagh.unitedeffects.com"
#  [[menu.footer]]
#    weight = 3
#    name = "Contact"
#    url = "/contact"
#  [[menu.footer]]
#    weight = 5
#    name = "Twitter"
#    url = "https://twitter.com/bomotlagh"
#  [[menu.footer]]
#    weight = 6
#    name = "United Effects"
#    url = "https://unitedeffects.com"

# The site's parameters
[params]

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Founder. Technology Expert. Revenue Focused. People Leader."
    subtitle = "Highly business centric, product and revenue focused, senior technology executive, who designs, and can also build, globally scalable SaaS products."

  [params.wrapper]
    enable = true
    title = "About Me"
    italic = "Seasoned and innovative enterprise leader"
    paragraph = "For 20 years I've been designing, building, integrating, and leading globally available SaaS and on-prem technologies, scaling products, and bridging disparate systems into cohesive platforms. I've been an architect, developer, manager, product leader, CTO, board advisor, change agent, and a Founder, CEO. I like to build things and help people achieve their goals."

  #[params.blog]
  #  enable = false
  #  title = "Get The Latest On What I'm doing"
  #  subtitle = "Catch up with me, anytime and anywhere"

  #[params.feature]
  #  enable = true
  #  title = "A Few Projects I Enjoyed"
  #  content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
  #  [params.feature.button]
  #    caption = "View Works"
  #    url = "#"

  [params.call]
    enable = true
    title = "Curious about United Effects?"
    paragraph = "United Effects focuses on post-M&A integration, aligning market positions, integrating product data, streamlining R&D, and ensuring scalable architectures to unlock M&A value and drive growth. Click below connect with the team and learn more."
    [params.call.button]
      url = "https://unitedeffects.com"

  [params.contact]
    enable = true
    title = "Contact Me"
    email = "borzou@bomotlagh.com"
    subtitle = "Happy to network!"
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "What can I help you with?"
      address = "Ambler, PA, USA"
      email = "borzou@bomotlagh.com"
      meeting = "https://calendly.com/ue-bo/hello"
    [params.contact.gmaps]
      title = "If you're local, lets grab a coffee!"
