title = "theBoEffect"
baseURL = "https://theboeffect.com"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Musings"
    url = "/blog"
  [[menu.header]]
    weight = 3
    name = "Contact Me"
    url = "/contact"
  [[menu.header]]
    weight = 4
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/bmotlagh"
  [[menu.header]]
    weight = 5
    name = "Medium Blog"
    url = "https://medium.com/@theboeffect"
  [[menu.header]]
    weight = 6
    name = "United Effects"
    url = "https://unitedeffects.com"
  [[menu.header]]
    weight = 7
    name = "UEAuth"
    url = "https://ueauth.io"

  [[menu.footer]]
    weight = 1
    name = "Home"
    url = "/"
  [[menu.footer]]
    weight = 3
    name = "Contact"
    url = "/contact"
  [[menu.footer]]
    weight = 2
    name = "About Me"
    url = "https://www.linkedin.com/in/bmotlagh"
  [[menu.footer]]
    weight = 4
    name = "Musings"
    url = "/blog"
  [[menu.footer]]
    weight = 5
    name = "Blog"
    url = "https://medium.com/@theboeffect"

# The site's parameters
[params]

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "A Builder and Dreamer"
    subtitle = "The simplest explanation: I like to explore ideas... what's yours?"

  [params.wrapper]
    enable = true
    title = "About Me"
    italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
    paragraph = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

# need to setup actual contact option...
  [params.contact]
    enable = true
    title = "Contact Me"
    subtitle = "I love partnering on interesting projects or providing any insights I can offer."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "What can I help you with?"
      address = "Philadelphia, PA, USA"
      email = "Email: borzou@theboeffect.com"
      twitter = "Twitter: @theBoEffect"
    [params.contact.gmaps]
      title = "If you're local, lets grab a coffee!"