title = "theBoEffect"
baseURL = "https://theboeffect.com"
languageCode = "en-us"
theme = "airspace-hugo"
publishDir = "docs"

[menu]

  [[menu.header]]
    weight = 2
    name = "About Me"
    url = "/#intro"
  [[menu.header]]
    weight = 3
    name = "Musings"
    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Services"
    url = "/#service"
  [[menu.header]]
    weight = 5
    name = "Contact Me"
    url = "/contact"
  [[menu.header]]
    weight = 6
    name = "Resume"
    url = "https://www.linkedin.com/in/bmotlagh"
  [[menu.header]]
    weight = 7
    name = "Medium Blog"
    url = "https://medium.com/@theboeffect"


  [[menu.footer]]
    weight = 1
    name = "Musings"
    url = "/blog"
  [[menu.footer]]
    weight = 2
    name = "Services"
    url = "/#service"
  [[menu.footer]]
    weight = 3
    name = "Contact"
    url = "/contact"
  [[menu.footer]]
    weight = 4
    name = "Resume"
    url = "https://www.linkedin.com/in/bmotlagh"
  [[menu.footer]]
    weight = 5
    name = "Medium Blog"
    url = "https://medium.com/@theboeffect"
  [[menu.footer]]
    weight = 6
    name = "Twitter"
    url = "https://twitter.com/theboeffect"

# The site's parameters
[params]

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "A Builder and Dreamer"
    subtitle = "The simplest explanation: I like to explore ideas... what's yours?"

  [params.wrapper]
    enable = true
    title = "About Me"
    italic = "''A man is known by the company he keeps; our character is reflected in our choice of friends.'' - Ralph Waldo Emerson (1803–1882)"
    paragraph = "My name is Borzou Motlagh, but most people call me Bo. In my career, I am an experienced technologist, leader and developer in the IT industry with expertise in software architecture, development, quality management, micro-service implementation, event-driven architectures, commercial product development, enterprise agile implementation, and the directing and management of large organizations. In short, I build software products at scale. In my life, I am an explorer of ideas, science, art and philosophy. I exercise to stay sharp and drink way too much coffee (though I think the science is in my favor in terms of my consumption). I find that the more of life you experience, the easier it is to find the patterns that helps us innovate. So I play music, I paint, I read everything from Karl Marx to Frank Herbert to Hawking and back, and I try to always keep an open mind."

  #[params.blog]
  #  enable = false
  #  title = "Get The Latest On What I'm doing"
  #  subtitle = "Catch up with me, anytime and anywhere"

  #[params.feature]
  #  enable = true
  #  title = "A Few Projects I Enjoyed"
  #  content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
  #  [params.feature.button]
  #    caption = "View Works"
  #    url = "#"

  [params.call]
    enable = true
    title = "Innovation Through Collaboration"
    paragraph = "I love thinking through interesting problems both technical and non-technical. If you think I can contribute, reach out and lets chat!"

  [params.contact]
    enable = true
    title = "Contact Me"
    email = "borzou@theboeffect.com"
    subtitle = "I love partnering on interesting projects or providing any insights I can offer."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "What can I help you with?"
      address = "Philadelphia, PA, USA"
      email = "Email: borzou@theboeffect.com"
      twitter = "Twitter: @theBoEffect"
    [params.contact.gmaps]
      title = "If you're local, lets grab a coffee!"